import { Button } from "@/components/ui/button";
import { Field, inputClass, Triple } from "./Fields";
import type { Interface, Joint } from "./types";
export function JointsEditor({ joints, bodies, onChange }: { joints: Joint[]; bodies: string[]; onChange: (j: Joint[]) => void }) {
  const update = (i: number, patch: Partial<Joint>) => onChange(joints.map((v, j) => j === i ? { ...v, ...patch } : v));
  return <details className="rounded border p-3"><summary className="cursor-pointer text-xs font-semibold">Joints · {joints.length}</summary><div className="mt-3 space-y-3"><p className="text-xs leading-5 text-muted-foreground">Build the instances first to populate body names. Joints connect rigid bodies for simulation.</p>{joints.map((j, i) => <div key={i} className="space-y-2 border-b pb-3"><div className="flex gap-2"><input aria-label="Joint name" className={inputClass} value={j.name || ""} onChange={e => update(i, { name: e.target.value })}/><Button size="xs" variant="ghost" onClick={() => onChange(joints.filter((_, n) => n !== i))}>Remove</Button></div><select aria-label="Joint type" className={inputClass} value={j.type} onChange={e => update(i, { type: e.target.value })}>{["fixed", "revolute", "prismatic"].map(v => <option key={v}>{v}</option>)}</select>{(["a", "b"] as const).map(key => <Field key={key} label={key === "a" ? "Parent body" : "Child body"}><select className={inputClass} value={j[key]} onChange={e => update(i, { [key]: e.target.value })}>{[...new Set([j[key], ...bodies])].map(v => <option key={v}>{v}</option>)}</select></Field>)}<Triple label="Anchor · mm" value={j.anchor} onChange={anchor => update(i, { anchor })}/>{j.type !== "fixed" && <><Triple label="Axis" value={j.axis} onChange={axis => update(i, { axis })}/><Field label={j.type === "revolute" ? "Limits · radians (optional)" : "Limits · mm (optional)"}><div className="flex gap-1">{[0,1].map(n => <input key={n} aria-label={`Joint limit ${n}`} type="number" step="any" className={inputClass} value={j.limits?.[n] ?? ""} onChange={e => update(i, { limits: e.target.value === "" ? undefined : [n === 0 ? Number(e.target.value) : j.limits?.[0] || 0, n === 1 ? Number(e.target.value) : j.limits?.[1] || 0] })}/>)}</div></Field></>}</div>)}<Button size="xs" variant="outline" disabled={bodies.length < 2} onClick={() => onChange([...joints, { name: `joint_${joints.length+1}`, type: "fixed", a: bodies[0], b: bodies[1], anchor: [0,0,0], axis: [0,0,1] }])}>Add joint</Button></div></details>;
}
export function InterfacesEditor({ interfaces, bodies, onChange }: { interfaces: Record<string, Interface>; bodies: string[]; onChange: (v: Record<string, Interface>) => void }) {
  return <details className="rounded border p-3"><summary className="cursor-pointer text-xs font-semibold">Connection interfaces · {Object.keys(interfaces).length}</summary><div className="mt-3 space-y-3"><p className="text-xs leading-5 text-muted-foreground">Named anchors are exported for reuse by parent assemblies.</p>{Object.entries(interfaces).map(([name, v]) => <div key={name} className="space-y-2"><div className="flex justify-between text-xs"><code>{name}</code><button onClick={() => { const next = { ...interfaces }; delete next[name]; onChange(next); }}>Remove</button></div><Field label="Body"><select className={inputClass} value={v.body} onChange={e => onChange({ ...interfaces, [name]: { ...v, body: e.target.value } })}>{[...new Set([v.body, ...bodies])].map(b => <option key={b}>{b}</option>)}</select></Field><Triple label="Anchor · mm" value={v.anchor} onChange={anchor => onChange({ ...interfaces, [name]: { ...v, anchor } })}/><Triple label="Axis" value={v.axis} onChange={axis => onChange({ ...interfaces, [name]: { ...v, axis } })}/></div>)}<Button size="xs" variant="outline" disabled={!bodies.length} onClick={() => { let n = 1; while (`mount_${n}` in interfaces) n++; onChange({ ...interfaces, [`mount_${n}`]: { body: bodies[0], anchor: [0,0,0], axis: [0,0,1] } }); }}>Add interface</Button></div></details>;
}
