import { useState } from "react";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Field, inputClass } from "./Fields";
import { asDefinition, makeId, type Kind, type ProjectState } from "./types";
export default function CreateDefinition({ kind, state, busy, onClose, onCreate }: { kind: Kind | null; state: ProjectState; busy: boolean; onClose: () => void; onCreate: (body: Record<string, unknown>, kind: Kind, id: string) => Promise<boolean> }) {
  const [label, setLabel] = useState(""); const [recipe, setRecipe] = useState("box"); const [hardware, setHardware] = useState(state.hardware[0]?.id || ""); const [assembly, setAssembly] = useState(Object.keys(state.manifest.assemblies || {})[0] || "");
  return <Dialog open={!!kind} onOpenChange={o => !o && onClose()}><DialogContent className="max-w-sm"><DialogHeader><DialogTitle>Create {kind === "component" ? "subcomponent" : kind}</DialogTitle></DialogHeader><div className="space-y-4"><Field label="Name"><input autoFocus aria-label="New definition name" className={inputClass} value={label} onChange={e => setLabel(e.target.value)}/></Field>{kind === "component" && <><Field label="Starting geometry"><select className={inputClass} value={recipe} onChange={e => setRecipe(e.target.value)}><option value="box">Box / link</option><option value="cylinder">Cylinder</option><option value="motor">Parameterized BLDC motor</option><option value="hardware">Hardware catalogue</option></select></Field>{recipe === "hardware" && <Field label="Catalogue part"><select className={inputClass} value={hardware} onChange={e => setHardware(e.target.value)}>{state.hardware.map(h => <option key={h.id}>{h.id}</option>)}</select></Field>}<p className="text-xs leading-5 text-muted-foreground">Creates an editable Python builder and parameter defaults in this project. Reuse it in any number of assembly instances.</p></>}{kind === "scene" && <Field label="Assembly"><select aria-label="New scene assembly" className={inputClass} value={assembly} onChange={e => setAssembly(e.target.value)}><option value="">Custom scene with instances</option>{Object.entries(state.manifest.assemblies || {}).map(([id,d]) => <option key={id} value={id}>{asDefinition(d).label || id}</option>)}</select></Field>}<Button className="w-full" disabled={busy || !makeId(label)} onClick={async () => { if (!kind) return; const id = makeId(label); const body = kind === "component" ? { action: "create_component", label, recipe, hardware } : { action: "save_definition", kind, name: id, definition: { label, parameters: assembly && kind === "scene" ? asDefinition(state.manifest.assemblies[assembly]).parameters || {} : {}, ...(kind === "scene" && assembly ? { assembly, config: {} } : { instances: [], joints: [] }), ...(kind === "scene" ? { environment: { ground: false }, settings: { gravity: -2000 } } : {}) } }; if (await onCreate(body, kind, id)) { setLabel(""); onClose(); } }}>Create {kind === "component" ? "subcomponent" : kind}</Button></div></DialogContent></Dialog>;
}
