import { Copy, Plus, Trash2, Layers, Box } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Field, inputClass, ParameterFields, Triple } from "./Fields";
import { asDefinition, type Instance, type ProjectState, type Values } from "./types";
export default function InstancesEditor({ state, instances, onChange, layoutOnly = false }: { layoutOnly?: boolean; state: ProjectState; instances: Instance[]; onChange: (v: Instance[]) => void }) {
  const choices = [ ...Object.entries(state.manifest.components || {}).map(([id, d]) => ({ value: `component:${id}`, label: asDefinition(d).label || id })), ...Object.entries(state.manifest.assemblies || {}).map(([id, d]) => ({ value: `assembly:${id}`, label: `${asDefinition(d).label || id} · assembly` })), ...state.dependencies.filter(d => d.present).flatMap(d => Object.keys(d.scenes).map(scene => ({ value: `project:${d.name}:${scene}`, label: `${d.name} / ${scene} · project` }))) ];
  const update = (i: number, patch: Partial<Instance>) => onChange(instances.map((v, j) => i === j ? { ...v, ...patch } : v));
  const unique = (base: string) => { let name = base, n = 2; while (instances.some(i => i.name === name)) name = `${base}_${n++}`; return name; };
  const parameters = (v: Instance): Values => v.component ? asDefinition(state.manifest.components[v.component] || {}).parameters || {} : v.assembly ? asDefinition(state.manifest.assemblies[v.assembly] || {}).parameters || {} : asDefinition(state.dependencies.find(d => d.name === v.project)?.scenes[v.scene || ""] || {}).parameters || {};
  return <div className="space-y-3"><div className="flex items-center justify-between"><h3 className="text-xs font-semibold">Instances · {instances.length}</h3><Button size="xs" variant="outline" disabled={layoutOnly || !choices.length} onClick={() => { const [kind, id, scene] = choices[0].value.split(":"); onChange([...instances, { name: unique(id), [kind]: id, ...(scene ? { scene } : {}), origin: [0,0,0], rotation: [0,0,0], config: {} }]); }}><Plus /> Add instance</Button></div>{!instances.length && <p className="text-xs leading-5 text-muted-foreground">Add reusable subcomponents or nest another assembly. Each instance has its own placement and configuration.</p>}{instances.map((v, i) => <div key={i} className="space-y-3 rounded border bg-card p-3"><div className="flex items-center gap-2">{v.component ? <Box size={13}/> : <Layers size={13}/>}<input readOnly={layoutOnly} aria-label={`Instance ${i+1} name`} className="min-w-0 flex-1 bg-transparent font-mono text-xs outline-none" value={v.name} onChange={e => update(i, { name: e.target.value })} /><button disabled={layoutOnly} title="Duplicate instance" onClick={() => onChange([...instances, { ...structuredClone(v), name: unique(v.name), origin: (v.origin || [0,0,0]).map((n, j) => j === 0 ? n + 50 : n) }])}><Copy size={13}/></button><button disabled={layoutOnly} title="Remove instance" onClick={() => onChange(instances.filter((_, j) => j !== i))}><Trash2 size={13}/></button></div><Field label="Definition"><select disabled={layoutOnly} aria-label={`Instance ${i+1} definition`} className={inputClass} value={v.component ? `component:${v.component}` : v.assembly ? `assembly:${v.assembly}` : `project:${v.project}:${v.scene}`} onChange={e => { const [kind, id, scene] = e.target.value.split(":"); const next: Instance = { name: v.name, origin: v.origin, rotation: v.rotation, config: {}, [kind]: id, ...(scene ? { scene } : {}) }; onChange(instances.map((v, j) => j === i ? next : v)); }}>{choices.map(c => <option key={c.value} value={c.value}>{c.label}</option>)}</select></Field><Triple label="Position · mm" value={v.origin} onChange={origin => update(i, { origin })}/><Triple label="Rotation · degrees" value={v.rotation} onChange={rotation => update(i, { rotation })}/>{Object.keys(parameters(v)).length > 0 && <details><summary className="cursor-pointer text-xs text-muted-foreground">Instance configuration</summary><div className="mt-3"><ParameterFields values={{ ...parameters(v), ...v.config }} onChange={config => update(i, { config })}/></div></details>}</div>)}</div>;
}
