import { useState } from "react";
import { GitBranch, GitCommitHorizontal } from "lucide-react";
import { Button } from "@/components/ui/button";
import { inputClass } from "./Fields";
import type { ProjectState } from "./types";
export default function RepositoryPanel({ state, busy, act, open }: { state: ProjectState; busy: boolean; act: (body: Record<string, unknown>) => Promise<boolean>; open: (path: string) => void }) {
  const [message, setMessage] = useState("");
  const [target, setTarget] = useState("");
  return <div className="space-y-4"><div className="rounded border bg-card p-3 text-xs"><div className="mb-2 flex items-center gap-2"><GitBranch size={14}/><b>{state.name}</b><span className="text-muted-foreground">{state.git.branch}</span></div><code className="text-muted-foreground">{state.git.commit.slice(0,12) || "No commits yet"}</code><p className="mt-2 leading-5 text-muted-foreground">These files belong to this project's Git repository.</p></div><div className="space-y-2"><h3 className="text-xs font-semibold">Changes · {state.git.changes.length}</h3><div className="max-h-48 overflow-auto rounded border bg-background p-2">{state.git.changes.length ? state.git.changes.map((v,i) => <pre key={i} className="whitespace-pre-wrap break-all text-[11px] leading-5">{v}</pre>) : <p className="text-xs text-muted-foreground">Working tree is clean</p>}</div><input aria-label="Commit message" className={inputClass} placeholder="Commit message" value={message} onChange={e => setMessage(e.target.value)}/><Button size="sm" className="w-full" disabled={busy || !message.trim() || !state.git.changes.length} onClick={async () => { if (await act({ action: "commit", message })) setMessage(""); }}><GitCommitHorizontal/> Commit changes in {state.name}</Button>{state.project && <Button size="xs" variant="outline" className="w-full" disabled={busy} onClick={() => void act({ action: "stage_pin" })}>Stage this revision in parent project</Button>}</div><div className="space-y-2 border-t pt-4"><h3 className="text-xs font-semibold">Included Git projects</h3>{state.dependencies.map(d => <button key={d.name} className="w-full rounded border p-3 text-left text-xs hover:bg-accent" onClick={() => open([state.project, d.path].filter(Boolean).join("/"))}><b>{d.name}</b><span className="float-right text-muted-foreground">{d.dirty ? "modified" : d.commit !== d.pinned ? "pin changed" : "pinned"}</span><code className="mt-1 block text-[10px] text-muted-foreground">{d.commit.slice(0,12) || "not checked out"}</code></button>)}<select aria-label="Include project" className={inputClass} value={target} onChange={e => setTarget(e.target.value)}><option value="">Choose project…</option>{state.available_projects.map(p => <option key={p}>{p}</option>)}</select><p className="text-[11px] leading-5 text-muted-foreground">Enable the library and commit its definitions in the child project first. The parent records a Git submodule pin.</p><div className="flex gap-2"><Button size="xs" variant="outline" disabled={busy || !target} onClick={() => void act({ action: "include_project", target })}>Include project</Button><Button size="xs" variant="outline" disabled={busy} onClick={() => void act({ action: "sync" })}>Sync submodules</Button></div></div></div>;
}
